version: "2"
services: 
  zentao:
    image: idoop/zentao:latest
    container_name: zentao
    ports:
      - "80:80"
      - "3306:3306"
    network_mode: "host"
    volumes:
      - zentao:/opt/zbox/
    restart: always
volumes:
  # 将./data修改为自己指定的路径.
  zentao: ./data