version: "2"
services: 
  zentao:
    image: idoop/zentao:latest
    container_name: zentao
    ports:
      - "80:80"
      - "3306:3306"
    network_mode: "host"
    environment:
    # specifies you own account and password.
      USER: "root"
      PASSWD: "123456"
      BIND_ADDRESS: "false"
    volumes:
    # specifies the path replace "./data".
      - ./data:/opt/zbox/
    restart: always
